# path: cloudbuild.yaml
substitutions:
  _SERVICE: madrid-enricher
  _REGION: europe-southwest1
  _IMAGE: gcr.io/$PROJECT_ID/${_SERVICE}

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE}:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE}:$SHORT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [
      'run','deploy','${_SERVICE}',
      '--image','${_IMAGE}:$SHORT_SHA',
      '--region','${_REGION}',
      '--platform','managed',
      '--allow-unauthenticated',
      '--update-env-vars','BQ_TABLE=rfp-database-464609.rfpdata.performing_arts_madrid,BQ_LOCATION=europe-southwest1',
      '--update-secrets','OPENAI_API_KEY=OPENAI_API_KEY:latest'
    ]

images:
- '${_IMAGE}:$SHORT_SHA'
